sudo: required
language: node_js
services:
    - docker

script:
    - echo "skipping tests"

after_success:
    - docker build -t abijeethdarwin/twitter-app-ui ./twitter-app-ui
    - docker build -t abijeethdarwin/twitter-app-api ./twitter-app-api
    - docker build -t abijeethdarwin/twitter-app-nginx ./twitter-app-nginx

    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the docker images
    - docker push abijeethdarwin/twitter-app-ui
    - docker push abijeethdarwin/twitter-app-api
    - docker push abijeethdarwin/twitter-app-nginx

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "Twitter-App"
    env: "Twitterapp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-377733686601"
    bucket_path: "twitter-app"
    on:
        branch: master
    access_key_id: $AWS_KEY_ID
    secret_access_key: $AWS_SECRET_KEY
