version: '3'
services:
    db:
        environment:
            MYSQL_ROOT_PASSWORD: root
        secrets:
            - mysql_root_pwd
    api:
        secrets:
            - twitter_consumer_key
            - twitter_consumer_secret
            - twitter_bearer_token
            - mysql_root_pwd
            - mysql_root_host
            - mysql_root_user
            - mysql_root_port
    
secrets:
    twitter_consumer_key:
        file: ./twitter_consumer_key.txt
    twitter_consumer_secret:
        file: ./twitter_consumer_secret.txt
    twitter_bearer_token:
        file: ./twitter_bearer_token.txt
    mysql_root_pwd:
        file: ./mysql_root_pwd.txt
    mysql_root_host:
        file: ./mysql_root_host.txt    
    mysql_root_user:
        file: ./mysql_root_user.txt
    mysql_root_port:
        file: ./mysql_root_port.txt
