version: '3'
services:
    db:
        container_name: twitter-app-db
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: twtappdb
        volumes:
            - ./twitter-app-db/data:/var/lib/mysql
            - ./twitter-app-db/config:/etc/mysql/conf.d
            - ./twitter-app-db/init:/docker-entrypoint-initdb.d
    web:
        stdin_open: true
        build: 
            context: ./twitter-app-ui
            dockerfile: Dockerfile.dev
        environment:
            CHOKIDAR_USEPOLLING: "true"
            NODE_ENV: dev
            ENV_NAME: local
        volumes: 
            - /usr/app/node_modules/
            - ./twitter-app-ui:/usr/app
    api:
        build:
            context: ./twitter-app-api
            dockerfile: Dockerfile.dev
        volumes: 
            - ./twitter-app-api:/usr/app
        environment:
            FLASK_DEBUG: 1
            PYTHONUNBUFFERED: 1
            FLASK_ENV: development
        depends_on:
            - db
    
    nginx:
        restart: always
        build: 
            context: ./twitter-app-nginx
            dockerfile: Dockerfile
        ports:
            - '3000:80'
        depends_on: 
            - api
            - web
