version: '3'
services:
    db:
        container_name: twitter-app-db
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: twt-app-db
        volumes:
            - ./twitter-app-db/data:/var/lib/mysql
            - ./twitter-app-db/config:/etc/mysql/conf.d
            - ./twitter-app-db/init:/docker-entrypoint-initdb.d
        ports:
            - '3306:3306'
    web:
        stdin_open: true
        build: 
            context: ./twitter-app-ui
            dockerfile: Dockerfile
        environment:
            CHOKIDAR_USEPOLLING: "true"
            NODE_ENV: dev
            ENV_NAME: local
        ports:
            - '3000:3000'
        volumes: 
            - /usr/app/node_modules/
            - ./twitter-app-ui:/usr/app
    api:
        build:
            context: ./twitter-app-api
            dockerfile: Dockerfile
        volumes: 
            - ./twitter-app-api:/usr/app
        ports:
            - '5000:5000'
        environment:
            FLASK_DEBUG: 1
            PYTHONUNBUFFERED: 1
            FLASK_ENV: development
        secrets:
            - twitter_consumer_key
            - twitter_consumer_secret
            - twitter_bearer_token
            - mysql_root_pwd
        depends_on:
            - db

secrets:
    twitter_consumer_key:
        file: ./twitter_consumer_key.txt
    twitter_consumer_secret:
        file: ./twitter_consumer_secret.txt
    twitter_bearer_token:
        file: ./twitter_bearer_token.txt
    mysql_root_pwd:
        file: ./mysql_root_pwd.txt
